### ISSUE TITLE
Support for Remote Cursor/Selection in Ace

### ISSUE THREAD

**Issue by Progyan1997** [Progyan1997/Operational-Transformation#60]

**Comment by Progyan1997** [comment]
@lapstjup, Okay now I feel stupid. Great catch and great fix. But now that I have you here, can you give a try to add tooltip/message same as monaco to announce the username?

**Comment by lapstjup** [comment]
@Progyan1997 Might give it a try in a separate issue. Would need to be familiar first as to how you have done it in monaco. I can see there is a dedicated file that goes by `cursor-widget.impl.ts` that I think is responsible for the tooltip stuff in monaco.

**Comment by Progyan1997** [comment]
Yes, you are right. Closing this one then!
